port: 8848
socks-port: 8838
mixed-port: 8868
allow-lan: False
mode: Global
log-level: info
external-controller: 127.0.0.1:9090
last-yaml: 1644799425304.yaml
system-proxy: False
auto-run: false
subConvert: https://sub.v1.mk/
localUI: http://127.0.0.1:9090/ui/
configIni: https://raw.githubusercontent.com/vveg26/SelfConfig/main/config.ini
clash-core: 
